### ISSUE TITLE
Please don't send spam

### ISSUE THREAD

**Issue by msikma** [irestful-labs/commodity-apis#1]
FOSS or not, spam is still spam. Post about your project on some public forum if you want feedback, 
but don't email people you don't know out of the blue.

<img width="644" alt="screen shot 2017-03-13 at 02 16 09" src="https://cloud.githubusercontent.com/assets/1507745/23838177/1821e22e-0793-11e7-9817-42d6d27ea757.png">

**Comment by steve-rodrigue** [comment]
I'm very sorry you didn't like my email request.  Ill make sure to never contact you and/or cold email again.  Sorry about that.

However, please note that cold emailing is not spam.  You might want to read this article that talks about it: https://www.leadfuze.com/what-is-cold-email-and-is-it-spam/ .  A lot of startups and projects does it very often.

Again, sorry for sending you this email.  It won't happen again.
